### ISSUE TITLE
Support two options to set connections: config + cli parameters (DSN)

### ISSUE THREAD

**Issue by Gaploid** [centralmind/gateway#31]
We need two options to set connection parameters:
1. through config file including database type and config could look like this:
    ```yaml
    kind: postgres
    hosts:
      - localhost
    user: readonly_user
    password: supersecretepassword
    database: postgres
    port: 5432
    ```
       
2. all connection details via parameters: db-type and db-connection accepting DSN strings like that: 
   ```
   gateway discover
   --db-type=postgres \
   --db-dsn=postgresql://username:password@host:port/dbname[?paramspec]
   ```
