### ISSUE TITLE
Incorrect database name when generating ClickHouse queries

### ISSUE THREAD

**Issue by lmangani** [centralmind/gateway#47]
Hello 👋 While testing around I noticed the ClickHouse connector (not sure if it applied to other dbs too) seems to consistently struggle with the database name. 

Here's an example: 

```yml
database:
    type: clickhouse
    connection: |
        type: clickhouse
        host: localhost
        user: default
        password: XXXXXXXXXX
        database: my_data
        port: 8123
        secure: false
```

The database name is provided in the connection and confirmed working since tables are detected and analyzed correctly. But when the gateway configuration is generated, the SELECT queries seem to ignore this: 

```yml
      endpoints:
            - http_method: GET
              http_path: /list
              mcp_method: get_list
              summary: Retrieve a list with pagination.
              description: 'Endpoint to fetch a paginated list. Example: `/list?offset=0&limit=100`'
              query: SELECT * FROM `public`.`some_table` LIMIT :limit OFFSET :offset
              is_array_result: true
```

As you con see somehow the `public` database makes its way into all the generated queries.
This is easy to fix, but might confuse some users.

I attempted with a couple different models _(Gemini, Qwen coder)_ with same results. I did not try other databases so for now I'm assuming this might be specific to this connector.
