### ISSUE TITLE
Simple Gateway API Example fail

### ISSUE THREAD

**Issue by VinMing** [centralmind/gateway#72]
follow [Simple Gateway API Example](https://docs.centralmind.ai/example/simple/#components)
my config.yaml
```
api:
  name: Awesome Readonly API
  description: ""
  version: 1.0.0
database:
  type: postgres
  connection:
    hosts:
      - 192.168.*.35
    user: mydb
    password: mydb
    database: mydb
    port: 5432
  tables:
    - name: gachi_teams
      columns:
        - name: id
          type: integer
          primary_key: false
          pii: false
        - name: team_name
          type: string
          primary_key: false
          pii: false
        - name: motto
          type: string
          primary_key: false
          pii: false
      endpoints:
        - http_method: GET
          http_path: /teams
          mcp_method: list_teams
          summary: Retrieve list of teams with pagination.
          description: 'This endpoint returns an array of team records. Example: GET /teams?offset=0&limit=5.'
          query: SELECT id, team_name, motto FROM gachi_teams ORDER BY id LIMIT :limit OFFSET :offset;
          is_array_result: true
          params:
            - name: offset
              type: integer
              location: query
              required: false
              default: 0
            - name: limit
              type: integer
              location: query
              required: false
              default: 5
        - http_method: GET
          http_path: /teams/{id}
          mcp_method: get_team_by_id
          summary: Retrieve a single team by its ID.
          description: 'This endpoint returns a single team record based on the provided ID. Example: GET /teams/1 returns the team with ID 1.'
          query: SELECT id, team_name, motto FROM gachi_teams WHERE id = :id LIMIT 1;
          is_array_result: false
          params:
            - name: id
              type: integer
              location: path
              required: true
        - http_method: GET
          http_path: /teams/total_count
          mcp_method: get_teams_total_count
          summary: Retrieve the total count of teams.
          description: 'This endpoint returns the total number of teams. Example: GET /teams/total_count returns an object with total_count.'
          query: SELECT count(*) AS total_count FROM gachi_teams;
          is_array_result: false
          params: []
    - name: gachi_personas
      columns:
        - name: strength_level
          type: integer
          primary_key: false
          pii: false
        - name: id
          type: integer
          primary_key: false
          pii: false
        - name: team_id
          type: integer
          primary_key: false
          pii: false
        - name: battle_cry
          type: string
          primary_key: false
          pii: false
        - name: special_move
          type: string
          primary_key: false
          pii: false
        - name: name
          type: string
          primary_key: false
          pii: false
        - name: favorite_drink
          type: string
          primary_key: false
          pii: false
      endpoints:
        - http_method: GET
          http_path: /personas
          mcp_method: list_personas
          summary: Retrieve list of personas with pagination.
          description: 'This endpoint returns a paginated array of persona records. Example: GET /personas?offset=0&limit=5 returns a list of personas.'
          query: SELECT strength_level, id, team_id, battle_cry, special_move, name, favorite_drink FROM gachi_personas ORDER BY id LIMIT :limit OFFSET :offset;
          is_array_result: true
          params:
            - name: offset
              type: integer
              location: query
              required: false
              default: 0
            - name: limit
              type: integer
              location: query
              required: false
              default: 5
        - http_method: GET
          http_path: /personas/{id}
          mcp_method: get_persona_by_id
          summary: Retrieve a single persona by its ID.
          description: 'This endpoint returns a single persona record based on the provided ID. Example: GET /personas/1 retrieves the persona with ID 1.'
          query: SELECT strength_level, id, team_id, battle_cry, special_move, name, favorite_drink FROM gachi_personas WHERE id = :id LIMIT 1;
          is_array_result: false
          params:
            - name: id
              type: integer
              location: path
              required: true
        - http_method: GET
          http_path: /personas/total_count
          mcp_method: get_personas_total_count
          summary: Retrieve the total count of personas.
          description: 'This endpoint returns the total number of persona records. Example: GET /personas/total_count returns an object with total_count.'
          query: SELECT count(*) AS total_count FROM gachi_personas;
          is_array_result: false
          params: []
plugins: {}

```

my docker-compose.yml
```
version: '3.8'

services:
  # postgres:
  #   image: postgres:latest
  #   container_name: postgres
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: mydb
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #     - ./csv:/var/lib/postgresql/csv
  #     - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount the seed data script

  gateway:
    build:
      context: ../..
      dockerfile: Dockerfile.build
      platforms:
        - linux/amd64
        - linux/arm64
    command:
      - start
      - --config
      - /usr/local/bin/config.yaml
      - --addr
      - ":8182"
    # depends_on:
    #   - postgres
    ports:
      - "8182:8182"
    volumes:
      - ./config.yaml:/usr/local/bin/config.yaml

# volumes:
#   postgres_data:
```

Start all services:
Terminal window
`docker-compose up`
log
```
[+] Running 1/1
 ✔ Container simple-gateway-1  Created                                                                                                                                      0.0s
Attaching to gateway-1
gateway-1  | [GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.
gateway-1  |
gateway-1  | [GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
gateway-1  |  - using env:      export GIN_MODE=release
gateway-1  |  - using code:     gin.SetMode(gin.ReleaseMode)
gateway-1  |
gateway-1  | [GIN-debug] GET    /raw/list_tables          --> github.com/centralmind/gateway/restgenerator.(*Rest).RegisterRoutes.(*Rest).ListTablesHandler.func3 (3 handlers)
gateway-1  | [GIN-debug] GET    /raw/discover_data        --> github.com/centralmind/gateway/restgenerator.(*Rest).RegisterRoutes.(*Rest).DiscoverDataHandler.func4 (3 handlers)
gateway-1  | [GIN-debug] GET    /raw/prepare_query        --> github.com/centralmind/gateway/restgenerator.(*Rest).RegisterRoutes.(*Rest).PrepareQueryHandler.func5 (3 handlers)
gateway-1  | [GIN-debug] GET    /raw/query                --> github.com/centralmind/gateway/restgenerator.(*Rest).RegisterRoutes.(*Rest).QueryHandler.func6 (3 handlers)
gateway-1  | INFO Gateway server started successfully!
gateway-1  | INFO MCP SSE server for AI agents is running at: http://localhost:8182/sse
gateway-1  | INFO REST API with Swagger UI is available at: http://localhost:8182/
```
why not see **gachi_teams endpoints** & **gachi_personas endpoints** with config.yaml 
E.g http://localhost:8182/teams , 404 page not found
