### ISSUE TITLE
Claude.ai can't connect to the Integration

### ISSUE THREAD

**Issue by BorisTyshkevich** [centralmind/gateway#81]
- I've started the gateway in K8s behind haproxy.
- Run it as:
```
 - args:
    - start
    - --config
    - /etc/gateway/config.yaml
    - --addr
    - :8090
    - --servers
    - https://XXX.cloud:443
```

- tested on https://playground.ai.cloudflare.com/ (got a list of tools)
- added new Organizational Integration to the claude.ai  (Team plan)
- Run Connect in "your Integrations" tab

Got an error:

```
There was an error connecting to XXX server. Please check your server URL and make sure your server handles auth correctly.
```

tried withoutthe  auth plugin and with:
```
plugins: 
    oauth:
        provider: "auth0"
        user_info_url: "https://ZZZ.auth0.com/userinfo"
        client_id=XXX
        client_secret=YYYY
        scopes:
          - "openid"
          - "profile"
          - "email"
        redirect_url: "https://mcp.XXX.cloud/oauth/callback"  # OAuth callback URL
        auth_url: "/oauth/authorize" # Gateway's authorization endpoint (optional)
        callback_url: "/oauth/callback" # Gateway's callback endpoint (optional)
```

If I add an Integration created from the URL provided by the centralmind.ai site, all works fine - I see tool names, can interact, etc.  @laskoviymishka  - could you show the config (plugins) used on the centralmind.ai site for reference?

Boris.
